<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\User1Controller;
use App\Http\Controllers\User2Controller;
use App\Http\Controllers\User3Controller;
use App\Http\Controllers\User4Controller;
use App\Http\Controllers\User5Controller;
use App\Http\Controllers\User6Controller;
use App\Http\Controllers\User7Controller;
use App\Http\Controllers\User8Controller;
use App\Http\Controllers\User9Controller;
use App\Http\Controllers\User10Controller;
use App\Http\Controllers\User11Controller;
use App\Http\Controllers\User12Controller;
use App\Http\Controllers\User13Controller;
use App\Http\Controllers\User14Controller;
use App\Http\Controllers\User15Controller;
use App\Http\Controllers\User16Controller;
use App\Http\Controllers\User17Controller;
use App\Http\Controllers\User18Controller;
use App\Http\Controllers\User19Controller;
use App\Http\Controllers\User20Controller;
use App\Http\Controllers\User21Controller;
use App\Http\Controllers\User22Controller;
use App\Http\Controllers\User23Controller;
use App\Http\Controllers\User24Controller;
use App\Http\Controllers\User25Controller;
use App\Http\Controllers\User26Controller;
use App\Http\Controllers\User27Controller;
use App\Http\Controllers\User28Controller;
use App\Http\Controllers\User29Controller;
use App\Http\Controllers\User30Controller;
use App\Http\Controllers\User31Controller;
use App\Http\Controllers\User32Controller;
use App\Http\Controllers\User33Controller;
use App\Http\Controllers\User34Controller;
use App\Http\Controllers\User35Controller;
use App\Http\Controllers\User36Controller;
use App\Http\Controllers\User37Controller;
use App\Http\Controllers\User38Controller;
use App\Http\Controllers\User39Controller;
use App\Http\Controllers\User40Controller;
use App\Http\Controllers\User41Controller;
use App\Http\Controllers\User42Controller;
use App\Http\Controllers\User43Controller;
use App\Http\Controllers\User44Controller;
use App\Http\Controllers\User45Controller;
use App\Http\Controllers\User46Controller;
use App\Http\Controllers\User47Controller;
use App\Http\Controllers\User48Controller;
use App\Http\Controllers\User49Controller;
use App\Http\Controllers\User50Controller;
use App\Http\Controllers\User51Controller;
use App\Http\Controllers\User52Controller;
use App\Http\Controllers\User53Controller;
use App\Http\Controllers\User54Controller;
use App\Http\Controllers\User55Controller;
use App\Http\Controllers\User56Controller;
use App\Http\Controllers\User57Controller;
use App\Http\Controllers\User58Controller;
use App\Http\Controllers\User59Controller;
use App\Http\Controllers\User60Controller;
use App\Http\Controllers\User61Controller;
use App\Http\Controllers\User62Controller;
use App\Http\Controllers\User63Controller;
use App\Http\Controllers\User64Controller;
use App\Http\Controllers\User65Controller;
use App\Http\Controllers\User66Controller;
use App\Http\Controllers\User67Controller;
use App\Http\Controllers\User68Controller;
use App\Http\Controllers\User69Controller;
use App\Http\Controllers\User70Controller;
use App\Http\Controllers\User71Controller;
use App\Http\Controllers\User72Controller;
use App\Http\Controllers\User73Controller;
use App\Http\Controllers\User74Controller;
use App\Http\Controllers\User75Controller;
use App\Http\Controllers\User76Controller;
use App\Http\Controllers\User77Controller;
use App\Http\Controllers\User78Controller;
use App\Http\Controllers\User79Controller;
use App\Http\Controllers\User80Controller;
use App\Http\Controllers\User81Controller;
use App\Http\Controllers\User82Controller;
use App\Http\Controllers\User83Controller;
use App\Http\Controllers\User84Controller;
use App\Http\Controllers\User85Controller;
use App\Http\Controllers\User86Controller;
use App\Http\Controllers\User87Controller;
use App\Http\Controllers\User88Controller;
use App\Http\Controllers\User89Controller;
use App\Http\Controllers\User90Controller;
use App\Http\Controllers\User91Controller;
use App\Http\Controllers\User92Controller;
use App\Http\Controllers\User93Controller;
use App\Http\Controllers\User94Controller;
use App\Http\Controllers\User95Controller;
use App\Http\Controllers\User96Controller;
use App\Http\Controllers\User97Controller;
use App\Http\Controllers\User98Controller;
use App\Http\Controllers\User99Controller;
use App\Http\Controllers\User100Controller;





Route::get('/user1',[User1Controller::class,'index']);
Route::get('/user2',[User2Controller::class,'index']);
Route::get('/user3',[User3Controller::class,'index']);
Route::get('/user4',[User4Controller::class,'index']);
Route::get('/user5',[User5Controller::class,'index']);
Route::get('/user6',[User6Controller::class,'index']);
Route::get('/user7',[User7Controller::class,'index']);
Route::get('/user8',[User8Controller::class,'index']);
Route::get('/user9',[User9Controller::class,'index']);
Route::get('/user10',[User10Controller::class,'index']);
Route::get('/user11',[User11Controller::class,'index']);
Route::get('/user12',[User12Controller::class,'index']);
Route::get('/user13',[User13Controller::class,'index']);
Route::get('/user14',[User14Controller::class,'index']);
Route::get('/user15',[User15Controller::class,'index']);
Route::get('/user16',[User16Controller::class,'index']);
Route::get('/user17',[User17Controller::class,'index']);
Route::get('/user18',[User18Controller::class,'index']);
Route::get('/user19',[User19Controller::class,'index']);
Route::get('/user20',[User20Controller::class,'index']);
Route::get('/user21',[User21Controller::class,'index']);
Route::get('/user22',[User22Controller::class,'index']);
Route::get('/user23',[User23Controller::class,'index']);
Route::get('/user24',[User24Controller::class,'index']);
Route::get('/user25',[User25Controller::class,'index']);
Route::get('/user26',[User26Controller::class,'index']);
Route::get('/user27',[User27Controller::class,'index']);
Route::get('/user28',[User28Controller::class,'index']);
Route::get('/user29',[User29Controller::class,'index']);
Route::get('/user30',[User30Controller::class,'index']);
Route::get('/user31',[User31Controller::class,'index']);
Route::get('/user32',[User32Controller::class,'index']);
Route::get('/user33',[User33Controller::class,'index']);
Route::get('/user34',[User34Controller::class,'index']);
Route::get('/user35',[User35Controller::class,'index']);
Route::get('/user36',[User36Controller::class,'index']);
Route::get('/user37',[User37Controller::class,'index']);
Route::get('/user38',[User38Controller::class,'index']);
Route::get('/user39',[User39Controller::class,'index']);
Route::get('/user40',[User40Controller::class,'index']);
Route::get('/user41',[User41Controller::class,'index']);
Route::get('/user42',[User42Controller::class,'index']);
Route::get('/user43',[User43Controller::class,'index']);
Route::get('/user44',[User44Controller::class,'index']);
Route::get('/user45',[User45Controller::class,'index']);
Route::get('/user46',[User46Controller::class,'index']);
Route::get('/user47',[User47Controller::class,'index']);
Route::get('/user48',[User48Controller::class,'index']);
Route::get('/user49',[User49Controller::class,'index']);
Route::get('/user50',[User50Controller::class,'index']);
Route::get('/user51',[User51Controller::class,'index']);
Route::get('/user52',[User52Controller::class,'index']);
Route::get('/user53',[User53Controller::class,'index']);
Route::get('/user54',[User54Controller::class,'index']);
Route::get('/user55',[User55Controller::class,'index']);
Route::get('/user56',[User56Controller::class,'index']);
Route::get('/user57',[User57Controller::class,'index']);
Route::get('/user58',[User58Controller::class,'index']);
Route::get('/user59',[User59Controller::class,'index']);
Route::get('/user60',[User60Controller::class,'index']);
Route::get('/user61',[User61Controller::class,'index']);
Route::get('/user62',[User62Controller::class,'index']);
Route::get('/user63',[User63Controller::class,'index']);
Route::get('/user64',[User64Controller::class,'index']);
Route::get('/user65',[User65Controller::class,'index']);
Route::get('/user66',[User66Controller::class,'index']);
Route::get('/user67',[User67Controller::class,'index']);
Route::get('/user68',[User68Controller::class,'index']);
Route::get('/user69',[User69Controller::class,'index']);
Route::get('/user70',[User70Controller::class,'index']);
Route::get('/user71',[User71Controller::class,'index']);
Route::get('/user72',[User72Controller::class,'index']);
Route::get('/user73',[User73Controller::class,'index']);
Route::get('/user74',[User74Controller::class,'index']);
Route::get('/user75',[User75Controller::class,'index']);
Route::get('/user76',[User76Controller::class,'index']);
Route::get('/user77',[User77Controller::class,'index']);
Route::get('/user78',[User78Controller::class,'index']);
Route::get('/user79',[User79Controller::class,'index']);
Route::get('/user80',[User80Controller::class,'index']);
Route::get('/user81',[User81Controller::class,'index']);
Route::get('/user82',[User82Controller::class,'index']);
Route::get('/user83',[User83Controller::class,'index']);
Route::get('/user84',[User84Controller::class,'index']);
Route::get('/user85',[User85Controller::class,'index']);
Route::get('/user86',[User86Controller::class,'index']);
Route::get('/user87',[User87Controller::class,'index']);
Route::get('/user88',[User88Controller::class,'index']);
Route::get('/user89',[User89Controller::class,'index']);
Route::get('/user90',[User90Controller::class,'index']);
Route::get('/user91',[User91Controller::class,'index']);
Route::get('/user92',[User92Controller::class,'index']);
Route::get('/user93',[User93Controller::class,'index']);
Route::get('/user94',[User94Controller::class,'index']); 
Route::get('/user95',[User95Controller::class,'index']);
Route::get('/user96',[User96Controller::class,'index']);
Route::get('/user97',[User97Controller::class,'index']);
Route::get('/user98',[User98Controller::class,'index']);
Route::get('/user99',[User99Controller::class,'index']);
Route::get('user100',[User100Controller::class,'index']);

